### ISSUE TITLE
Wrong subproject assignment

### ISSUE THREAD

**Issue by rachelcsimmons** [skibitsky/alfred-timing#13]
Hey, I have noticed an issue with the wrong subproject being selected when it has the same name as another subproject that's under a different parent project. I'm not quite sure if it's ignoring subprojects completely, or if it's breaking because of the duplicate names. 

For example, I have two parent projects, ABC Company and XYZ Company. They both have a subproject "Pre and Post Work."

- ABC Company->Pre and Post Work
- XYZ Company->Pre and Post Work

Each week, I do task "Weekly Task" which is always under ABC Company->Pre and Post Work.

When I initiate this workflow and type "Weekly Task," it matches my task and surfaces it in the list, which is great. When I hit enter and start this task, it shows in my taskbar that I am doing Weekly Task, but when I edit the currently running task via the taskbar, it's just a standalone project "Pre and Post Work," not under any parent project.

**Comment by skibitsky** [comment]
Hey @rachelcsimmons, thank you very much for creating this issue! 

I pushed a fix in v1.3.0, you can update by running `npm i -g alfred-timing@latest`.
This update fixes the bug you mentioned, as well as makes project chain appear below every task instead of just project name. 

![Screenshot 2023-01-10 at 21 05@2x](https://user-images.githubusercontent.com/15127974/211669304-5a042296-814f-4825-b661-0f16e69ec357.png)
